# Generated by Django 5.0.6 on 2024-06-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('summary', models.CharField(max_length=250, verbose_name='Summary')),
                ('facebook_link', models.CharField(max_length=1000, verbose_name='Facebook Link')),
                ('instagram_link', models.CharField(max_length=1000, verbose_name='Instagram Link')),
                ('twitter_link', models.CharField(max_length=1000, verbose_name='twitterLink')),
                ('linkedin_link', models.CharField(max_length=1000, verbose_name='LinkedIn Link')),
                ('github_link', models.CharField(max_length=1000, verbose_name='Github Link')),
                ('resume', models.FileField(upload_to='resume', verbose_name='Resume')),
                ('profile_image', models.ImageField(upload_to='profile', verbose_name='Profile Image')),
                ('about_image', models.ImageField(upload_to='profile', verbose_name='About Image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Project Description')),
                ('image', models.ImageField(upload_to='project', verbose_name='Project Image')),
                ('github_link', models.CharField(max_length=1000, verbose_name='Github LinK')),
                ('demo_link', models.CharField(max_length=1000, verbose_name='Demo LinK')),
            ],
        ),
    ]
