# Generated by Django 5.0.6 on 2024-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saroj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Project Description'),
        ),
    ]
